# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DsvCli < Formula
  desc "⚡ A cross-platform swiss army knife tool for DevOps secrets management from Delinea."
  homepage "https://github.com/DelineaXPM/dsv-cli"
  version "1.39.8"
  license "Apache-2.0 license"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DelineaXPM/dsv-cli/releases/download/v1.39.8/dsv-darwin-arm64", using: CurlDownloadStrategy
      sha256 "4c2381c89d1ec5a20ea049a5a6ed77722da39939648ba94d52f619fe528e426e"

      def install
        bin.install "dsv-darwin-arm64" => "dsv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DelineaXPM/dsv-cli/releases/download/v1.39.8/dsv-darwin-x64", using: CurlDownloadStrategy
      sha256 "a19b4343fd03e9a793099be0fc22caba2d3d4a2adeac268bf1095ab5c0147e84"

      def install
        bin.install "dsv-darwin-x64" => "dsv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/DelineaXPM/dsv-cli/releases/download/v1.39.8/dsv-linux-x64", using: CurlDownloadStrategy
      sha256 "9903ccb6bb9275a23a7a4f1a53613d012115fbcd525fecc98b08af45e91e6e7f"

      def install
        bin.install "dsv-linux-x64" => "dsv"
      end
    end
  end

  test do
    assert_equal "1.39.8", shell_output("#{bin}/dsv --version").strip
  end
end
