# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DsvCli < Formula
  desc "⚡ A cross-platform swiss army knife tool for DevOps secrets management from Delinea."
  homepage "https://github.com/DelineaXPM/dsv-cli"
  version "1.41.0"
  license "Apache-2.0 license"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/DelineaXPM/dsv-cli/releases/download/v1.41.0/dsv-darwin-x64", using: CurlDownloadStrategy
      sha256 "ed6bffd88326ddb625fbdf1c61033fc10c8b31afcac6afbe0ba56c66e31a398a"

      def install
        bin.install "dsv-darwin-x64" => "dsv"
      end
    end
    on_arm do
      url "https://github.com/DelineaXPM/dsv-cli/releases/download/v1.41.0/dsv-darwin-arm64", using: CurlDownloadStrategy
      sha256 "a9e8e5e89cda8cd2f217e263dfcfc703245534aefe74acff526320113e730583"

      def install
        bin.install "dsv-darwin-arm64" => "dsv"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DelineaXPM/dsv-cli/releases/download/v1.41.0/dsv-linux-x64", using: CurlDownloadStrategy
        sha256 "1f97924c73743664fb2350fc743801df05ba748866908b9fb4f8f445047a6389"

        def install
          bin.install "dsv-linux-x64" => "dsv"
        end
      end
    end
  end

  test do
    assert_equal "1.41.0", shell_output("#{bin}/dsv --version").strip
  end
end
